spring:
  profiles:
    active: cloud
---
spring:
  profiles: cloud
server:
  port: 1111
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-77.cfapps.io/eureka/
  instance:
    hostname: ui-search-77.cfapps.io
    nonSecurePort: 80
ribbon:
  eureka:
    enabled: true
---
spring:
  profiles: development
server:
  port: 1111
eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery-77.cfapps.io/eureka/
  instance:
    preferIpAddress: true
ribbon:
  eureka:
    enabled: false